name             'opsworks-utils-cookbook'
maintainer       'Paul Allen'
maintainer_email 'cloud-devops@cornell.edu'
license          'All rights reserved'
description      'Standard recipes for Cloud DevOps Team'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'aws'
gem              'aws-sdk-core'
gem              'cucloud'